name: 0.0.0-assets-ci-$(Rev:rr)

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - projects/[app-name]/public/*
      - projects/[app-name]/assets.yml
pool:
  name: "Server2022"

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/projects/[app-name]/public"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/dist/[app-name]/assets"
    displayName: "Copy assets to dist folder"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/projects/ui-components/src/assets"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/dist/[app-name]/assets"
    displayName: "Copy ui-components assets to dist folder"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/projects/ui-components/src/assets"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/dist/[app-name]/assets"
    displayName: "Copy ui-components assets to dist folder"

  - task: OctopusPack@4
    inputs:
      PackageId: "Laromedel.[AppName].Assets"
      PackageFormat: "NuPkg"
      PackageVersion: "$(Build.BuildNumber)"
      SourcePath: "$(Build.SourcesDirectory)/dist/[app-name]/assets"
      OutputPath: "$(Build.ArtifactStagingDirectory)"
    displayName: "Create OctopusPackage artifact"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "OctopusPackage"
      publishLocation: "Container"
    displayName: "Publish OctopusPackage artifact"
