export enum EnklaOrd {
    ARM = 'arm',
    LA = 'la',
    LO = 'lo',
    MIL = 'mil',
    MOS = 'mos',
    ORM = 'orm',
    OS = 'os',
    RAM = 'ram',
    RIM = 'rim',
    RO = 'ro',
    ROS = 'ros',
    SA = 'sa',
    SAL = 'sal',
    SIL = 'sil',
    SO = 'so',
    SOL = 'sol',
}