export enum Fordon {
    AMBULANS = 'ambulans',
    BARGNINGSBIL = 'bärgningsbil',
    BIL = 'bil',
    BRANDBIL = 'brandbil',
    BUSS = 'buss',
    GAFFELTRUCK = 'gaffeltruck',
    GRAVMASKIN = 'grävmaskin',
    HJULLASTARE = 'hjullastare',
    KRANBIL = 'kranbil',
    LASTBIL = 'lastbil',
    MOPED = 'moped',
    POLISBIL = 'polisbil',
    SOPBIL = 'sopbil',
    TAXI = 'taxi',
    TIMMERBIL = 'timmerbil',
    TRAKTOR = 'traktor',
}