export enum Idrottshall {
    BADMINTONRACKET = 'badmintonracket',
    BALANSBOLL = 'balansboll',
    BANK = 'bank',
    BASKETKORG = 'basketkorg',
    BOLLAR = 'bollar',
    BOLLVAGN = 'bollvagn',
    HOPPREP = 'hopprep',
    IDROTTSHALL = 'idrottshall',
    LANGMATTA = 'långmatta',
    LIAN = 'lian',
    MAL = 'mål',
    RIBBSTOL = 'ribbstol',
    RINGAR = 'ringar',
    ROCKRING = 'rockring',
    SARG = 'sarg',
    TJOCKMATTA = 'tjockmatta',
}