export enum Kanslor {
    ARG = 'arg',
    AVUNDSJUK = 'avundsjuk',
    FORVANAD = 'förvånad',
    FRUSTRERAD = 'frustrerad',
    GLAD = 'glad',
    INTRESSERAD = 'intresserad',
    IRRITERAD = 'irriterad',
    KAR = 'kär',
    LEDSEN = 'ledsen',
    NOJD = 'nöjd',
    NYFIKEN = 'nyfiken',
    OROLIG = 'orolig',
    PIGG = 'pigg',
    RADD = 'rädd',
    STOLT = 'stolt',
    TROTT = 'trött',
}