export enum Alfabetet {
    A = 'a',
    B = 'b',
    C = 'c',
    D = 'd',
    E = 'e',
    F = 'f',
    G = 'g',   
    H = 'h',
    I = 'i',
    J = 'j',
    K = 'k',
    L = 'l',
    M = 'm',
    N = 'n',
    O = 'o',
    P = 'p',
    Q = 'q',
    R = 'r',
    S = 's',
    T = 't',
    U = 'u',
    V = 'v',
    W = 'w',
    X = 'x',
    Y = 'y',
    Z = 'z',
    Å = 'å',
    Ä = 'ä',
    Ö = 'ö'
}

export enum EnklaOrd {
    ARM = 'arm',
    LA = 'la',
    LO = 'lo',
    MIL = 'mil',
    MOS = 'mos',
    ORM = 'orm',
    OS = 'os',
    RAM = 'ram',
    RIM = 'rim',
    RO = 'ro',
    ROS = 'ros',
    SA = 'sa',
    SAL = 'sal',
    SIL = 'sil',
    SO = 'so',
    SOL = 'sol',
}

export enum Kanslor {
    ARG = 'arg',
    AVUNDSJUK = 'avundsjuk',
    FORVANAD = 'förvånad',
    FRUSTRERAD = 'frustrerad',
    GLAD = 'glad',
    INTRESSERAD = 'intresserad',
    IRRITERAD = 'irriterad',
    KAR = 'kär',
    LEDSEN = 'ledsen',
    NOJD = 'nöjd',
    NYFIKEN = 'nyfiken',
    OROLIG = 'orolig',
    PIGG = 'pigg',
    RADD = 'rädd',
    STOLT = 'stolt',
    TROTT = 'trött',
}

export enum Skolord {
    DATOR = 'dator',
    IDROTTSHALL = 'idrottshall',
    LAROBOK = 'lärobok',
    MATSAL = 'matsal',
    PENNA = 'penna',
    RAST = 'rast',
    SCHEMA = 'schema',
    SKOLBANK = 'skolbänk',
    SKOLGARD = 'skolgård',
    SKRIVBOK = 'skrivbok',
    SUDDGUMMI = 'suddgummi',
    SURFPLATTA = 'surfplatta',
    TEXTILSLÖJD = 'textilslöjd',
    TRASLOJD = 'traslöjd',
    WHITEBOARD = 'whiteboard',
}