
export enum Idrottshall {
    BADMINTONRACKET = 'badmintonracket',
    BALANSBOLL = 'balansboll',
    BANK = 'bank',
    BASKETKORG = 'basketkorg',
    BOLLAR = 'bollar',
    BOLLVAGN = 'bollvagn',
    HOPPREP = 'hopprep',
    IDROTTSHALL = 'idrottshall',
    LANGMATTA = 'långmatta',
    LIAN = 'lian',
    MAL = 'mål',
    RIBBSTOL = 'ribbstol',
    RINGAR = 'ringar',
    ROCKRING = 'rockring',
    SARG = 'sarg',
    TJOCKMATTA = 'tjockmatta',
}

export enum Rorselse {
    ALA = 'åla',
    BALANSERA = 'balansera',
    FANGA = 'fånga',
    FLYTA = 'flyta',
    GA = 'gå',
    HANGA = 'hänga',
    HOPPA = 'hoppa',
    KASTA = 'kasta',
    KRYPA = 'krypa',
    LIGGA = 'ligga',
    SIMMA = 'simma',
    SITTA = 'sitta',
    SMYGA = 'smyga',
    SNURRA = 'snurra',
    SPRINGA = 'springa',
    STA = 'stå',
}

export enum Sport {
    BADMINTON = 'badminton',
    BORDTENNIS = 'bordtennis',
    BOWLING = 'bowling',
    BOXNING = 'boxning',
    DANS = 'dans',
    FOTBOLL = 'fotboll',
    FRIIDROTT = 'friidrott',
    GYMNASITK = 'gymnastik',
    INNEBANDY = 'innebandy',
    ISHOCKEY = 'ishockey',
    KAMPSPORT = 'kampsport',
    RIDNING = 'ridning',
    SIMNING = 'simning',
    SLALOM = 'slalom',
    TENNIS = 'tennis',
    TYNGDLYFTNING = 'tyngdlyftning',
}

export enum Vattensakerhet {
    ARSTID = 'årstid',
    BRYGGA = 'brygga',
    FLYTVAST = 'flytväst',
    HOST = 'höst',
    IS = 'is',
    ISDUBBAR = 'isdubbar',
    ISVAK = 'isvak',
    KALLT = 'kallt',
    LIVBOJ = 'livboj',
    REP = 'rep',
    SJO = 'sjö',
    SOMMAR = 'sommar',
    VAN = 'vän',
    VAR = 'vår',
    VARMT = 'varmt',
    VINTER = 'vinter',
}