export enum Rorselse {
    ALA = 'åla',
    BALANSERA = 'balansera',
    FANGA = 'fånga',
    FLYTA = 'flyta',
    GA = 'gå',
    HANGA = 'hänga',
    HOPPA = 'hoppa',
    KASTA = 'kasta',
    KRYPA = 'krypa',
    LIGGA = 'ligga',
    SIMMA = 'simma',
    SITTA = 'sitta',
    SMYGA = 'smyga',
    SNURRA = 'snurra',
    SPRINGA = 'springa',
    STA = 'stå',
}