export enum Sport {
    BADMINTON = 'badminton',
    BORDTENNIS = 'bordtennis',
    BOWLING = 'bowling',
    BOXNING = 'boxning',
    DANS = 'dans',
    FOTBOLL = 'fotboll',
    FRIIDROTT = 'friidrott',
    GYMNASITK = 'gymnastik',
    INNEBANDY = 'innebandy',
    ISHOCKEY = 'ishockey',
    KAMPSPORT = 'kampsport',
    RIDNING = 'ridning',
    SIMNING = 'simning',
    SLALOM = 'slalom',
    TENNIS = 'tennis',
    TYNGDLYFTNING = 'tyngdlyftning',
}