export enum Fordon {
    AMBULANS = 'ambulans',
    BARGNINGSBIL = 'bärgningsbil',
    BIL = 'bil',
    BRANDBIL = 'brandbil',
    BUSS = 'buss',
    GAFFELTRUCK = 'gaffeltruck',
    GRAVMASKIN = 'grävmaskin',
    HJULLASTARE = 'hjullastare',
    KRANBIL = 'kranbil',
    LASTBIL = 'lastbil',
    MOPED = 'moped',
    POLISBIL = 'polisbil',
    SOPBIL = 'sopbil',
    TAXI = 'taxi',
    TIMMERBIL = 'timmerbil',
    TRAKTOR = 'traktor',
}

export enum Frukt {
    ANANAS = 'ananas',
    APELSIN = 'apelsin',
    APPLE = 'äpple',
    BANAN = 'banan',
    CLEMENTIN = 'clementin',
    DADEL = 'dadel',
    GRANATAPPLE = 'granatäpple',
    HONUNGSMELON = 'honungsmelon',
    KIWI = 'kiwi',
    KOKOSNOT = 'kokosnöt',
    MANGO = 'mango',
    PARON = 'päron',
    PERSIKA = 'persika',
    PLOMMON = 'plommon',
    VATTENMELON = 'vattenmelon',
    VINDRUVA = 'vindruva',
}

export enum GronsakerOchRotfrukter {
    ARTOR = 'ärtor',
    AVOKADO = 'avokado',
    BLOMKAL = 'blomkål',
    BONOR = 'bönor',
    BROCCOLI = 'broccoli',
    GURKA = 'gurka',
    LOK = 'lök',
    MAJS = 'majs',
    MOROT = 'morot',
    PAPRIKA = 'paprika',
    POTATIS = 'potatis',
    PURJOLÖK = 'purjolök',
    RODKAL = 'rödkål',
    SALLAD = 'sallad',
    TOMAT = 'tomat',
    VITKAL = 'vitkål',
}

export enum Koksredskap {
    BUNKE = 'bunke',
    DURKSLAG = 'durkslag',
    ELVISP = 'elvisp',
    GAFFEL = 'gaffel',
    GLAS = 'glas',
    KASTRULL = 'kastrull',
    KNIV = 'kniv',
    KOKSTANG = 'koktång',
    RIVJARN = 'rivjärn',
    SKARBRADA = 'skärbräda',
    SKED = 'sked',
    STEKPANNA = 'stekpanna',
    TALLRIK = 'tallrik',
    VASS_KNIV = 'vass kniv',
    VISP = 'visp',
    VITLOKSPRESS = 'vitlökspress',
}

export enum Livsmedel {
    AGG = 'ägg',
    FILMJOLK = 'filmjölk',
    FLINGOR = 'flingor',
    KETCHUP = 'ketchup',
    KNACKEBROD = 'knäckebröd',
    KRYDDOR = 'kryddor',
    MATOLJA = 'matolja',
    MJOL = 'mjöl',
    MJOLK = 'mjölk',
    MJUKT_BROD = 'mjukt bröd',
    OST = 'ost',
    RIS = 'ris',
    SENAP = 'senap',
    SMOR = 'smör',
    SPAGETTI = 'spagetti',
    VATTEN = 'vatten',
}

export enum Religion {
    BIBEL = 'bibel',
    BONEMATTA = 'bönematta',
    IMAM = 'imam',
    ISLAM = 'islam',
    JUDENDOM = 'judendom',
    KORANEN = 'koranen',
    KRISTENDOM = 'kristendom',
    KYRKA = 'kyrka',
    MENORA = 'menora',
    MOSKE = 'moské',
    NATTVARD = 'nattvard',
    PRAST = 'präst',
    RABBIN = 'rabbin',
    RELIGION = 'religion',
    SYNAGOGA = 'synagoga',
    TORA = 'tora',
}

export enum Samhallet {
    ALDREOMSORG = 'äldreomsorg',
    AMBULANS = 'ambulans',
    BIBLIOTEK = 'bibliotek',
    BRANDKAR = 'brandkår',
    DOMSTOL = 'domstol',
    EL = 'el',
    FANGELSE = 'fängelse',
    FORSKOLA = 'förskola',
    KOLLEKTIVTRAFIK = 'kollektivtrafik',
    POLIS = 'polis',
    SJUKHUS = 'sjukhus',
    SKOLA = 'skola',
    SOPHAMTNING = 'sophämtning',
    TANDLAKARE = 'tandläkare',
    VAG = 'väg',
    VATTEN = 'vatten',
}

export enum Trafik {
    BIL = 'bil',
    BILVAG = 'bilväg',
    CYKEL = 'cykel',
    CYKELBANA = 'cykelbana',
    CYKELHJALM = 'cykelhjälm',
    FORGANGARE = 'fotgängare',
    GANGBANA = 'gångbana',
    HOGER = 'höger',
    OVERGANGSSTALLE = 'övergångsställe',
    RAKT_FRAM = 'rakt fram',
    REFLEX = 'reflex',
    RONDELL = 'rondell',
    TRAFIKLJUS = 'trafikljus',
    TROTTOAR = 'trottoar',
    VAGMARKE = 'vägmarke',
    VANSTER = 'vänster',
}