export enum Vattensakerhet {
    ARSTID = 'årstid',
    BRYGGA = 'brygga',
    FLYTVAST = 'flytväst',
    HOST = 'höst',
    IS = 'is',
    ISDUBBAR = 'isdubbar',
    ISVAK = 'isvak',
    KALLT = 'kallt',
    LIVBOJ = 'livboj',
    REP = 'rep',
    SJO = 'sjö',
    SOMMAR = 'sommar',
    VAN = 'vän',
    VAR = 'vår',
    VARMT = 'varmt',
    VINTER = 'vinter',
}