export enum Antal {
    ETT = 'ett',
    TVA = 'två',
    TRE = 'tre',
    FYRA = 'fyra',
    FEM = 'fem',
    SEX = 'sex',
    SJU = 'sju',
    ATTA = 'åtta',
    NIO = 'nio',
    TIO = 'tio',
    ELVA = 'elva',
    TOLV = 'tolv',
    TRETTON = 'tretton',
    FJORTON = 'fjorton',
    FEMTON = 'femton',
    SEXTON = 'sexton',
}

export enum Djur {
    ALG = 'älg',
    EKORRE = 'ekorre',
    FAR = 'far',
    FLUGA = 'fluga',
    GETING = 'geting',
    GRIS = 'gris',
    HARE = 'hare',
    HAST = 'häst',
    HONA = 'höna',
    HUMLA = 'humla',
    KO = 'ko',
    MYGGA = 'mygga',
    MYRA = 'myra',
    NYCKELPIGA = 'nyckelpiga',
    RAV = 'räv',
    SPINDEL = 'spindel',
}

export enum Klader {
    BYXOR = 'byxor',
    HALSDUK = 'halsduk',
    JACKA = 'jacka',
    JEANS = 'jeans',
    KJOL = 'kjol',
    KLANNING = 'klänning',
    MOSSA = 'mössa',
    OVERALL = 'overall',
    REGNBYXOR = 'regnbyxor',
    REGNJACKA = 'regnjacka',
    SKOR = 'skor',
    STOVLAR = 'stövlar',
    STRUMPOR = 'strumpor',
    TSHIRT = 't-shirt',
    TROJA = 'tröja',
    VANTAR = 'vantar',
}

export enum Kroppen {
    ARM = 'arm',
    AXEL = 'axel',
    BEN = 'ben',
    FINGER = 'finger',
    FOT = 'fot',
    HALS = 'hals',
    HAND = 'hand',
    HAR = 'hår',
    HUVUD = 'huvud',
    KNÄ = 'knä',
    MUN = 'mun',
    NAGEL = 'nagel',
    NASA = 'näsa',
    OGON = 'ögon',
    ORA = 'öra',
    TA = 'tå',
}

export enum Lagesord {
    BAKOM = 'bakom',
    BREDVID = 'bredvid',
    FORST = 'först',
    HOGER = 'höger',
    HOGT = 'högt',
    I = 'i',
    LÅGT = 'lågt',
    LANGT_BORT = 'långt bort',
    MELLAN = 'mellan',
    NARA = 'nära',
    OVER = 'över',
    PA = 'på',
    SIST = 'sist',
    UNDER = 'under',
    VANSTER = 'vänster',
}

export enum Pengar {
    AFFAR = 'affär',
    BANKKORT = 'bankkort',
    BETALA = 'betala',
    EN_KRONA = 'en krona',
    FEM_KRONA = 'fem krona',
    FEMHUNDRALAPP = 'femhundralapp',
    FEMTIOLAPP = 'femtiolapp',
    HUNNDRALAPP = 'hundralapp',
    PENGAR = 'pengar',
    SWISH = 'swish',
    TIO_KRONA = 'tio krona',
    TJUGOLAPP = 'tjugolapp',
    TUSENLAPP = 'tusenlapp',
    TVA_KRONA = 'två krona',
    TVAHUNDRALAPP = 'tvåhundralapp',
    VAXEL = 'växel',
}

export enum Vardagsteknik {
    BRODROST = 'brödrost',
    DAMMSUGARE = 'dammsugare',
    DATOR = 'dator',
    DISKMASKIN = 'diskmaskin',
    ELVISP = 'elvisp',
    FLAKT = 'fläkt',
    HORLURAR = 'hörlurar',
    KAFFEBRYGGARE = 'kaffebryggare',
    MIKROVAGSUGN = 'mikrovågsugn',
    MIXER = 'mixer',
    SPIS = 'spis',
    SURFPLATTA = 'surfplatta',
    TELEFON = 'telefon',
    TV = 'tv',
    VAFFELJARN = 'våffeljärn',
    VATTENKOKARE = 'vattenkokare',
}

export enum Vaxter {
    APPELTRAD = 'äppelträd',
    BJORK = 'björk',
    BLABAR = 'blåbär',
    BLAKLOCKA = 'blåklocka',
    GRAN = 'gran',
    HALLON = 'hallon',
    HJORTRON = 'hjortron',
    JORDGUBBE = 'jordgubbe',
    LINGON = 'lingon',
    MASKROS = 'maskros',
    PARONTRAD = 'päronträd',
    ROS = 'ros',
    SMULTRON = 'smultron',
    TALL = 'tall',
    TULPAN = 'tulpan',
    VINBAR = 'vinbär',
}