name: 3.0.1-assets-ci-$(Rev:rr)

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - projects/lika-lika/public/*
      - projects/lika-lika/assets.yml
pool:
  name: "Server2022"

variables:
  - group: OctopusDeployVariables

steps:
  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/projects/lika-lika/public"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/dist/lika-lika/assets"
    displayName: "Copy assets to dist folder"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(Build.SourcesDirectory)/projects/ui-components/src/assets"
      Contents: "**"
      TargetFolder: "$(Build.SourcesDirectory)/dist/lika-lika/assets"
    displayName: "Copy ui-components assets to dist folder"

  - task: OctopusPackNuGet@6
    name: pkg
    displayName: 'Package NuPkg For Octopus Deploy'
    inputs:
      PackageId: "Laromedel.LikaLika.Assets"
      PackageVersion: '$(Build.BuildNumber)'
      NuGetDescription: 'Lika Lika Frontend'
      NuGetAuthors: 'SPSM'
      SourcePath: "$(Build.SourcesDirectory)/dist/lika-lika/assets"
      OutputPath: "$(Build.ArtifactStagingDirectory)"

  - task: OctopusPush@6
    displayName: 'Push package to Octopus'
    inputs:
      OctoConnectedServiceName: $(connectionName)
      Space: $(spaceName)
      Packages: '$(Build.ArtifactStagingDirectory)/Laromedel.LikaLika.Assets.$(Build.BuildNumber).nupkg'
      Replace: true

  - task: OctopusCreateRelease@6
    name: create_release
    displayName: 'Create Octopus Release'
    inputs:
      OctoConnectedServiceName: $(connectionName)
      Space: $(spaceName)
      ReleaseNumber: '$(Build.BuildNumber)'
      Project: Lika-Lika
      Packages: 'Laromedel.LikaLika.Assets:$(Build.BuildNumber)'
      Channel: Assets
