name: 3.0.2-frontend-ci-$(Rev:rr)

trigger:
  branches:
    include:
      - develop
  paths:
    include:
      - projects/lika-lika/*
      - projects/ui-component/*
      - projects/media/*
      - projects/utility/*
      - projects/games/*
      - shared/*
      - package.json

    exclude:
      - projects/lika-lika/src/assets/*
      - projects/lika-lika/assets.yml
pool:
  name: "Server2022"

variables:
  - group: OctopusDeployVariables
steps:
  - checkout: self
    clean: false
    fetchDepth: 1

  - task: NodeTool@0
    inputs:
      versionSpec: "20.x"
    displayName: "Install Node.js"

  - task: Npm@1
    inputs:
      command: "install"
    displayName: "Run npm install"

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run lint media"
    displayName: "Check linting for media library"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci media'
    env:
      CI: true
    displayName: 'Run unit tests for media'

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run build media"
    displayName: "Build media library"

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run lint ui-components"
    displayName: "Check linting for ui-components library"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci ui-components'
    env:
      CI: true
    displayName: 'Run unit tests for ui-components'

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run build ui-components"
    displayName: "Build ui-components library"

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run lint utility"
    displayName: "Check linting for utility library"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci utility'
    env:
      CI: true
    displayName: 'Run unit tests for utility'

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run build utility"
    displayName: "Build utility library"

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run lint games"
    displayName: "Check linting for games library"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci games'
    env:
      CI: true
    displayName: 'Run unit tests for games'

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run build games"
    displayName: "Build games library"

  - task: Npm@1
    inputs:
      command: 'custom'
      customCommand: 'run test:ci lika-lika'
    env:
      CI: true
    displayName: 'Run unit tests for lika-lika'

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run lint lika-lika"
    displayName: "Check linting for lika-lika project"

  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run build lika-lika"
    displayName: "Build lika-lika project"

  - task: OctopusPackNuGet@6
    name: pkg
    displayName: 'Package NuPkg For Octopus Deploy'
    inputs:
      PackageId: "Laromedel.LikaLika.Frontend"
      PackageVersion: '$(Build.BuildNumber)'
      NuGetDescription: 'Lika Lika Frontend'
      NuGetAuthors: 'SPSM'
      SourcePath: "$(Build.SourcesDirectory)/dist/lika-lika/browser"
      OutputPath: "$(Build.ArtifactStagingDirectory)"

  - task: OctopusPush@6
    displayName: 'Push Packages to Octopus'
    inputs:
      OctoConnectedServiceName: $(connectionName)
      Space: $(spaceName)
      Packages: '$(Build.ArtifactStagingDirectory)/Laromedel.LikaLika.Frontend.$(Build.BuildNumber).nupkg'
      Replace: true

  - task: OctopusCreateRelease@6
    name: create_release
    displayName: 'Create Octopus Release'
    inputs:
      OctoConnectedServiceName: $(connectionName)
      Space: $(spaceName)
      ReleaseNumber: '$(Build.BuildNumber)'
      Project: Lika-Lika
      Packages: 'Laromedel.LikaLika.Frontend:$(Build.BuildNumber)'
      Channel: Frontend
