export interface IMemoryGameConfig {
  TIMEOUT_LENGTH_MEDIA_MS: number;
  TIME_UNTIL_CARDS_FLIP_MS: number;
  MEAN_MEDIA_DURATION_MS: number;
  DEAL_ANIMATION_DELAY: number;
  TIME_AFTER_FLIP_OVER_TO_PLAY_AUDIO_MS: number;
  MEDIA_TIMEOUT_ID: "MEDIA_TIMEOUT";
}

export const MemoryGameConfig: IMemoryGameConfig = {
  TIMEOUT_LENGTH_MEDIA_MS: 600 + 300,
  TIME_UNTIL_CARDS_FLIP_MS: 600,
  MEAN_MEDIA_DURATION_MS: 2500,
  DEAL_ANIMATION_DELAY: 150,
  TIME_AFTER_FLIP_OVER_TO_PLAY_AUDIO_MS: 300,
  MEDIA_TIMEOUT_ID: "MEDIA_TIMEOUT" as const,
};
